```{r}
library(tidyverse)
library(ggVennDiagram)
```

---

```{r}
load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240219_ensembl_annovar/GRCh38_PLP/df_ClinVar_GRCh38_PLP_annovar_ensembl.RData")
load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240219_ensembl_annovar/GRCh38_BLB/df_ClinVar_GRCh38_BLB_annovar_ensembl.RData")

load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240227_ensembl_snpeff/GRCh38_PLP/df_ClinVar_GRCh38_PLP_snpeff_ensembl.RData")
load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240227_ensembl_snpeff/GRCh38_BLB/df_ClinVar_GRCh38_BLB_snpeff_ensembl.RData")

load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240226_ensembl_vep/GRCh38_PLP/df_ClinVar_GRCh38_PLP_vep_ensembl.RData")
load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240226_ensembl_vep/GRCh38_BLB/df_ClinVar_GRCh38_BLB_vep_ensembl.RData")

```


# Transcript Count

```{r}
df_ClinVar_GRCh38_PLP_annovar_ensembl %>%
  select(ENST) %>%
  distinct() %>%
  nrow()

df_ClinVar_GRCh38_BLB_annovar_ensembl %>%
  select(ENST) %>%
  distinct() %>%
  nrow()
```

```{r}
df_ClinVar_GRCh38_PLP_snpeff_ensembl %>%
  select(ENST) %>%
  distinct() %>%
  nrow()

df_ClinVar_GRCh38_BLB_snpeff_ensembl %>%
  select(ENST) %>%
  distinct() %>%
  nrow()
```

```{r}
df_ClinVar_GRCh38_PLP_vep_ensembl %>%
  select(Feature) %>%
  distinct() %>%
  nrow()

df_ClinVar_GRCh38_BLB_vep_ensembl %>%
  select(Feature) %>%
  distinct() %>%
  nrow()
```

```{r}

ANNOVAR <- union(
  df_ClinVar_GRCh38_PLP_annovar_ensembl$ENST,
  df_ClinVar_GRCh38_BLB_annovar_ensembl$ENST
)

SnpEff <- union(
  df_ClinVar_GRCh38_PLP_snpeff_ensembl$ENST,
  df_ClinVar_GRCh38_BLB_snpeff_ensembl$ENST
)

VEP <- union(
  df_ClinVar_GRCh38_PLP_vep_ensembl$Feature,
  df_ClinVar_GRCh38_BLB_vep_ensembl$Feature
)

All <- union(union(ANNOVAR, SnpEff), VEP) %>% sort()

```

```{r}
length(ANNOVAR)/length(All)
length(SnpEff)/length(All)
length(VEP)/length(All)
```

```{r fig.width=3, fig.height=3}
barplot_TXcount_ensembl <- tibble(
  Annotator = c("ANNOVAR", "SnpEff", "VEP"),
  Fraction = c(length(ANNOVAR)/length(All), length(SnpEff)/length(All), length(VEP)/length(All)),
  Count = c(length(ANNOVAR), length(SnpEff), length(VEP))
) %>%
  mutate(Annotator = factor(Annotator, levels = c("ANNOVAR", "SnpEff", "VEP"))) %>%
  ggplot(aes(x = Annotator, y = Fraction)) +
  geom_bar(stat="identity", fill = "#619CFF") +
  geom_text(aes(label = Count), vjust=1.3, color="white", position = position_dodge(0.9), size = 5) +
  theme(
    panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color = NA), #transparent plot bg
    axis.ticks.y = element_line(linewidth = 1, color="black") , 
    axis.ticks.length.y = unit(0.5, "cm"),
    axis.line.y = element_line(linewidth = 1, colour = "black"),
    axis.text.y = element_text(size = 10, face = "bold"),
    axis.text.x = element_text(size = 10, face = "bold"),
    panel.grid.major = element_blank() #remove major gridlines
    # legend.background = element_rect(fill='transparent'), #transparent legend bg
    # legend.box.background = element_rect(fill='transparent') #transparent legend panel
  ) +
  xlab("") +
  # ylim(0.1, 0.9) +
  ylab("Fraction of total transcript")
```

```{r}
ggsave("barplot_TXcount_ensembl.png", barplot_TXcount_ensembl, bg='transparent', width = unit(3, "cm"), height = unit(3, "cm"))
```

沒數字版本
```{r fig.width=3, fig.height=3}
barplot_TXcount_ensembl <- tibble(
  Annotator = c("ANNOVAR", "SnpEff", "VEP"),
  Fraction = c(length(ANNOVAR)/length(All), length(SnpEff)/length(All), length(VEP)/length(All)),
  Count = c(length(ANNOVAR), length(SnpEff), length(VEP))
) %>%
  mutate(Annotator = factor(Annotator, levels = c("ANNOVAR", "SnpEff", "VEP"))) %>%
  ggplot(aes(x = Annotator, y = Fraction)) +
  geom_bar(stat="identity", fill = "#619CFF") +
  # geom_text(aes(label = Count), vjust=1.3, color="white", position = position_dodge(0.9), size = 5) +
  theme(
    panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color = NA), #transparent plot bg
    axis.ticks.y = element_line(linewidth = 1, color="black") , 
    axis.ticks.length.y = unit(0.5, "cm"),
    axis.line.y = element_line(linewidth = 1, colour = "black"),
    axis.text.y = element_text(size = 10, face = "bold"),
    axis.text.x = element_text(size = 10, face = "bold"),
    panel.grid.major = element_blank() #remove major gridlines
    # legend.background = element_rect(fill='transparent'), #transparent legend bg
    # legend.box.background = element_rect(fill='transparent') #transparent legend panel
  ) +
  xlab("") +
  # ylim(0.1, 0.9) +
  ylab("Fraction of total transcript")
```

```{r}
ggsave("barplot_TXcount_ensembl_noNum.png", barplot_TXcount_ensembl, bg='transparent', width = unit(3, "cm"), height = unit(3, "cm"))
```

---

```{r}
Venn_TxVariants_Full <- Venn(list(
  ANNOVAR = ANNOVAR,
  SnpEff = SnpEff,
  VEP = VEP
))


data <- process_data(Venn_TxVariants_Full)
```

```{r fig.width=5, fig.height=5}
ggplot() +
  # 1. region count layer
  geom_polygon(aes(X, Y, fill = id, group = id), 
          data = venn_regionedge(data),
          show.legend = FALSE) +
  # 2. set edge layer
  geom_path(aes(X, Y, group = id),
            color="grey",
            data = venn_setedge(data),
            linewidth = 1,
            show.legend = FALSE) +
  # 3. set label layer
  geom_text(aes(X, Y, label = name), 
            fontface = "bold",
            data = venn_setlabel(data)) +
  # 4. region label layer
  geom_label(aes(X, Y, label = count), 
             data = venn_regionlabel(data),
             size = 5,
             alpha = 0.5) +
  coord_equal() +
  theme_void()
```

```{r}
526+0+335+20777+5845+3+41070

526/68556
0/68556
335/68556
20777/68556
5845/68556
3/68556
41070/68556

```
526/68556=0.00767256
0/68556=0
335/68556=0.004886516
20777/68556=0.3030661
5845/68556=0.08525877
3/68556=4.375985e-05
41070/68556=0.5990723



```{r fig.width=5, fig.height=5}
ggVenn_AllTx <- ggplot() +
  # 1. region count layer
  geom_polygon(aes(X, Y, fill = id, group = id), 
          data = venn_regionedge(data),
          show.legend = FALSE) +
  # 2. set edge layer
  geom_path(aes(X, Y, group = id),
            color="grey",
            data = venn_setedge(data),
            linewidth = 1,
            show.legend = FALSE) +
  # 3. set label layer
  geom_text(aes(X, Y, label = name), 
            fontface = "bold",
            data = venn_setlabel(data)) +
  # 4. region label layer
  geom_label(aes(X, Y, label = count), 
             data = venn_regionlabel(data),
             size = 5,
             alpha = 0.5) +
  coord_equal() +
  theme(
    panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank() #remove major gridlines
  ) +
  theme_void()
```

```{r}
ggsave("Venn_TxVariants_Ensembl.png", ggVenn_AllTx, bg='transparent', width = 5, height = 5)
```

```{r}
data$regionData %>% 
  mutate(item = map_chr(item, paste, collapse = ",")) %>%
  write_tsv(file = "Venn_TxVariants_Ensembl.tsv")
```



