```{r}
library(tidyverse)
library(ggVennDiagram)
```

---

```{r}
load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240219_refseq_annovar/CSQ_concordance/CSQ_ClinVar_GRCh38_BLB_annovar_refseq.RData")
load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240219_refseq_annovar/CSQ_concordance/CSQ_ClinVar_GRCh38_PLP_annovar_refseq.RData")

load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240227_refseq_snpeff/CSQ_concordance/CSQ_ClinVar_GRCh38_BLB_snpeff_refseq.RData")
load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240227_refseq_snpeff/CSQ_concordance/CSQ_ClinVar_GRCh38_PLP_snpeff_refseq.RData")

load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240226_refseq_vep/CSQ_concordance/CSQ_ClinVar_GRCh38_BLB_vep_refseq.RData")
load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240226_refseq_vep/CSQ_concordance/CSQ_ClinVar_GRCh38_PLP_vep_refseq.RData")

```

---

# All Transcript

```{r}

ANNOVAR_allDF <- bind_rows(
  CSQ_ClinVar_GRCh38_BLB_annovar_refseq %>% select(key, NM, Consequence),
  CSQ_ClinVar_GRCh38_PLP_annovar_refseq %>% select(key, NM, Consequence)
) %>%
  # 639,245
  distinct()
  # 664,425

SnpEff_allDF <- bind_rows(
  CSQ_ClinVar_GRCh38_BLB_snpeff_refseq %>% select(key, NM, Consequence),
  CSQ_ClinVar_GRCh38_PLP_snpeff_refseq %>% select(key, NM, Consequence)
) %>%
  # 188,812
  distinct()
  # 188,812

VEP_allDF <- bind_rows(
  CSQ_ClinVar_GRCh38_BLB_vep_refseq %>% select(key, Feature, Consequence),
  CSQ_ClinVar_GRCh38_PLP_vep_refseq %>% select(key, Feature, Consequence)
) %>%
  # 1,397,641
  distinct() %>%
  mutate(NM = str_extract(Feature, '[^\\.]*')) %>%
  select(key, NM, Consequence)
  # 1,397,641

```

---

```{r}
 VEP_allDF %>%
  group_by(Consequence) %>%
  count() %>%
  arrange(-n)
```

---

```{r}
ANNOVAR <- ANNOVAR_allDF %>% 
  mutate(ANNOVAR = str_c(key, ":", NM, ":", Consequence)) %>%
  select(ANNOVAR) %>% unlist(use.names = F) %>% sort()
# 639245

SnpEff <- SnpEff_allDF %>% 
  mutate(SnpEff = str_c(key, ":", NM, ":", Consequence)) %>%
  select(SnpEff) %>% unlist(use.names = F) %>% sort()
# 188812

VEP <- VEP_allDF %>%
  mutate(VEP = str_c(key, ":", NM, ":", Consequence)) %>%
  select(VEP) %>% unlist(use.names = F) %>% sort()
# 1397641

All <- union(union(ANNOVAR, SnpEff), VEP) %>% sort()
# 1407525

```

---

```{r}
Venn_AllTx <- Venn(list(
  ANNOVAR = ANNOVAR,
  SnpEff = SnpEff,
  VEP = VEP
))


data <- process_data(Venn_AllTx)
```

```{r fig.width=5, fig.height=5}
ggplot() +
  # 1. region count layer
  geom_polygon(aes(X, Y, fill = id, group = id), 
          data = venn_regionedge(data),
          show.legend = FALSE) +
  # 2. set edge layer
  geom_path(aes(X, Y, group = id),
            color="grey",
            data = venn_setedge(data),
            linewidth = 1,
            show.legend = FALSE) +
  # 3. set label layer
  geom_text(aes(X, Y, label = name), 
            fontface = "bold",
            data = venn_setlabel(data)) +
  # 4. region label layer
  geom_label(aes(X, Y, label = count), 
             data = venn_regionlabel(data),
             size = 5,
             alpha = 0.5) +
  coord_equal() +
  theme_void()
```

```{r}
9392+165+327+443882+185806+2514+765439

9392/1407525
165/1407525
327/1407525
443882/1407525
185806/1407525
2514/1407525
765439/1407525

```

9392/1407525=0.006672706
165/1407525=0.000117227
327/1407525=0.0002323227
443882/1407525=0.3153635
185806/1407525=0.132009
2514/1407525=0.001786114
765439/1407525=0.5438191

```{r fig.width=5, fig.height=5}
ggVenn_AllTx <- ggplot() +
  # 1. region count layer
  geom_polygon(aes(X, Y, fill = id, group = id), 
          data = venn_regionedge(data),
          show.legend = FALSE) +
  # 2. set edge layer
  geom_path(aes(X, Y, group = id),
            color="grey",
            data = venn_setedge(data),
            linewidth = 1,
            show.legend = FALSE) +
  # 3. set label layer
  geom_text(aes(X, Y, label = name), 
            fontface = "bold",
            data = venn_setlabel(data)) +
  # 4. region label layer
  geom_label(aes(X, Y, label = count), 
             data = venn_regionlabel(data),
             size = 5,
             alpha = 0.5) +
  coord_equal() +
  theme(
    panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank() #remove major gridlines
  ) +
  theme_void()
```

```{r}
ggsave("Venn_CSQ_allTx_RefSeq.png", ggVenn_AllTx, bg='transparent', width = 5, height = 5)
```

```{r}
data$regionData %>% 
  mutate(item = map_chr(item, paste, collapse = ",")) %>%
  write_tsv(file = "Venn_CSQ_allTx_RefSeq.png.tsv")
```


















