```{r}
library(tidyverse)
library(ggVennDiagram)
```

---

要接在`Fig3 HGVSp RefSeq Venn GRCh38.Rmd`之後

```{r}
rm(
  df_ClinVar_GRCh38_PLP_annovar_refseq,
  df_ClinVar_GRCh38_BLB_annovar_refseq,
  df_ClinVar_GRCh38_PLP_snpeff_refseq,
  df_ClinVar_GRCh38_BLB_snpeff_refseq,
  df_ClinVar_GRCh38_PLP_vep_refseq,
  df_ClinVar_GRCh38_BLB_vep_refseq
)
```

```{r}
rm(
  AAnameList,
  ANNOVAR,
  SnpEff,
  VEP,
  All,
  Venn_TxVariants_Full,
  data
)
```

```{r}
load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240219_ClinVar_VCF/df_clinvar_GRCh38_PLP_Tx1.RData")
load("~/rproj/Paper3Annot_2024/ClinVar20240107/20240219_ClinVar_VCF/df_clinvar_GRCh38_BLB_Tx1.RData")
```

```{r}
ClinVar_NM <- union(df_clinvar_GRCh38_BLB_Tx1$NM, df_clinvar_GRCh38_PLP_Tx1$NM) %>% sort()
```

---

```{r}

ANNOVAR_clinvar <- ANNOVAR_HGVSp_refseq_all %>%
  # 384,599
  filter(NM %in% ClinVar_NM)
  # 139,031

SnpEff_clinvar <- SnpEff_HGVSp_refseq_all %>%
  # 127,063
  filter(NM %in% ClinVar_NM)
  # 123,871

VEP_clinvar <- VEP_HGVSp_refseq_all %>%
  # 682,720
  filter(NM %in% ClinVar_NM)
  # 141,039

```


```{r}
ANNOVAR <- ANNOVAR_clinvar %>% 
  mutate(ANNOVAR = str_c(key, ":", NM, ":", ANNOVAR)) %>%
  select(ANNOVAR) %>% unlist(use.names = F) %>% sort()
# 139031

SnpEff <- SnpEff_clinvar %>% 
  mutate(SnpEff = str_c(key, ":", NM, ":", SnpEff)) %>%
  select(SnpEff) %>% unlist(use.names = F) %>% sort()
# 123871

VEP <- VEP_clinvar %>%
  mutate(VEP = str_c(key, ":", NM, ":", VEP)) %>%
  select(VEP) %>% unlist(use.names = F) %>% sort()
# 141039

All <- union(union(ANNOVAR, SnpEff), VEP) %>% sort()
# 144051

```

```{r}
Venn_TxVariants_ClinVar <- Venn(list(
  ANNOVAR = ANNOVAR,
  SnpEff = SnpEff,
  VEP = VEP
))


data <- process_data(Venn_TxVariants_ClinVar)
```

```{r fig.width=5, fig.height=5}
ggplot() +
  # 1. region count layer
  geom_polygon(aes(X, Y, fill = id, group = id), 
          data = venn_regionedge(data),
          show.legend = FALSE) +
  # 2. set edge layer
  geom_path(aes(X, Y, group = id),
            color="grey",
            data = venn_setedge(data),
            linewidth = 1,
            show.legend = FALSE) +
  # 3. set label layer
  geom_text(aes(X, Y, label = name), 
            fontface = "bold",
            data = venn_setlabel(data)) +
  # 4. region label layer
  geom_label(aes(X, Y, label = count), 
             data = venn_regionlabel(data),
             size = 5,
             alpha = 0.5) +
  coord_equal() +
  theme_void()
```

```{r}
1475+152+1385+121059+16345+1275+2360

1475/144051
152/144051
1385/144051
121059/144051
16345/144051
1275/144051
2360/144051

```

1475/144051=0.01023943
152/144051=0.001055182
1385/144051=0.00961465
121059/144051=0.8403899
16345/144051=0.1134668
1275/144051=0.008851032
2360/144051=0.01638309


```{r fig.width=5, fig.height=5}
Venn_TxVariants_ClinVar <- ggplot() +
  # 1. region count layer
  geom_polygon(aes(X, Y, fill = id, group = id), 
          data = venn_regionedge(data),
          show.legend = FALSE) +
  # 2. set edge layer
  geom_path(aes(X, Y, group = id),
            color="grey",
            data = venn_setedge(data),
            linewidth = 1,
            show.legend = FALSE) +
  # 3. set label layer
  geom_text(aes(X, Y, label = name), 
            fontface = "bold",
            data = venn_setlabel(data)) +
  # 4. region label layer
  geom_label(aes(X, Y, label = count), 
             data = venn_regionlabel(data),
             size = 5,
             alpha = 0.5) +
  coord_equal() +
  theme(
    panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank() #remove major gridlines
  ) +
  theme_void()
```

```{r}
ggsave("HGVSp/Venn_HGVSp_ClinVarTx.png", Venn_TxVariants_ClinVar, bg='transparent', width = 5, height = 5)
```

```{r}
data$regionData %>% 
  mutate(item = map_chr(item, paste, collapse = ",")) %>%
  write_tsv(file = "HGVSp/Venn_HGVSp_ClinVarTx.tsv")
```

```{bash}
head HGVSp/Venn_HGVSp_ClinVarTx.tsv
```



